### ISSUE TITLE
Swiping profiles doesn't always trigger the change

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#100]
I've noticed sometimes when swiping profiles that it doesn't always switch to the new profile. Not sure what might be causing this. I think I noticed it more when swiping to the clear profile.

Also every once and a while the keyboard will crash when selecting a profile from the table. I haven't been able to recreate this while debugging the app so no idea whats causing that.

**Comment by Danwakeem** [comment]
I fixed the keyboard crash when selecting from the profile table but I have not merged it yet because I think my branch was behind the develop branch and I am going to manually merge the changes.

**Comment by Danwakeem** [comment]
Okay I merged. I didn't mess up your last commit did I?

**Comment by Danwakeem** [comment]
Okay never mind something happened after I merged and the fix doesn't work.

**Comment by Danwakeem** [comment]
Nowww I fixed the crash on the profile tables. Sorry for blowing it.

**Comment by Danwakeem** [comment]
Okay I also fixed the Swipe profile latency. Done.
