### ISSUE TITLE
Shareable profiles

### ISSUE THREAD

**Issue by Danwakeem** [Danwakeem/enigma#155]

**Comment by SlayterDev** [comment]
7af0e12b8ab16dbb4e1dc7f563540cf183b13438 adds this, but no URL sharing.

**Comment by Danwakeem** [comment]
How should I do it with out a URL?

**Comment by SlayterDev** [comment]
Well the current solution I implemented shares the QR code as an image. The user can save it or post it somewhere. If we setup a URL scheme though, we can share it that way.

**Comment by Danwakeem** [comment]
Ohhh okay I see what you mean

**Comment by Danwakeem** [comment]
So I implemented this with a URL scheme. You should check it out. I merged it into develop. I encrypted the data in the url scheme so you can send it to someone through a text message. Let me know what you think. @SlayterDev

**Comment by SlayterDev** [comment]
Looks great! But I found a layout issue with the help text I'll post in another issue.
