### ISSUE TITLE
Add Touch ID to Passcode View

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#21]

**Comment by SlayterDev** [comment]
Touch ID fails every time

**Comment by SlayterDev** [comment]
Strangely it appears to work when not debugging the app

**Comment by Danwakeem** [comment]
I don't know if it woul help if you know this but it works when I do it on my phone.

**Comment by SlayterDev** [comment]
Yeah it works on mine too. Just not when I had it connected this morning. I'll try it through Xcode again later tonight.

On Feb 7, 2015, at 7:57 PM, Danwakeem <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know if it woul help if you know this but it works when I do it on my phone.

-

**Comment by SlayterDev** [comment]
Gonna mark this as done.
