### ISSUE TITLE
Integrate CoreData

### ISSUE THREAD

**Issue by Danwakeem** [Danwakeem/enigma#34]
Adding the CoreData model to the main app.

**Comment by Danwakeem** [comment]
Got this working I just need to fix the merge issues.

**Comment by SlayterDev** [comment]
https://github.com/Danwakeem/enigma/commit/4bf5d003da6c685311323622398b1fbfc8a95a78

I got your back :+1:

**Comment by Danwakeem** [comment]
Hahaha thanks man!😎
