### ISSUE TITLE
Crash on startup. Unwrapping optional value

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#47]
Dan something seems to be messing up in the core data setup. Specifically here:

    lazy var applicationDocumentsDirectory: NSURL = {
            // The directory the application uses to store the Core Data store file. This code uses a directory      named "com.Danwakeem.Brace_Editor" in the application's documents Application Support directory.
            //let urls = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains:     .UserDomainMask)
            //return urls[urls.count-1] as NSURL
        
        let urls = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("group.com.enigma")
        return urls! // <- the offending line
        
        }()

Not sure what the deal is

@Danwakeem

**Comment by SlayterDev** [comment]
Thought maybe reinstalling the app would help but it still crashes

**Comment by jakesinger** [comment]
I think the line 'let urls' needs to be 'let urls?', so that when the '!' symbol is used, it can evaluate to nil in the event of failure

**Comment by Danwakeem** [comment]
No you have to add the app group to your project. It is failing as nil because it isn't set up on your xcode project.

**Comment by Danwakeem** [comment]
[Okay here is how to enable the app group.] (https://www.dropbox.com/s/7azgyan6oxyca5v/EnableAppGroup.mpg?dl=0) Make sure you add the app group to both targets. (the containing app and the keyboard)

**Comment by SlayterDev** [comment]
Did you make an App ID through apple? Because I can't make one now with that bundle ID.

**Comment by Danwakeem** [comment]
Ahh man yeah I bet I did. Hang on I must have to add you guys to a development team or something.

**Comment by Danwakeem** [comment]
Can you add it if you go to the certificates section at developer.apple.com under the app group subsection?

**Comment by SlayterDev** [comment]
Nope. You wanna just redo it through my account and Ill add yall on as team members?

**Comment by Danwakeem** [comment]
Yeah sure that would be fine with me.

**Comment by SlayterDev** [comment]
Ok i think you need to delete the app ids and app group from your account. Also comment with your Apple ID

**Comment by Danwakeem** [comment]
Okay I will delete it real quick. My Apple ID is Danwakeem@gmail.com

**Comment by Danwakeem** [comment]
The app IDs are under com.SlayterDev should I still delete it?

**Comment by SlayterDev** [comment]
Yeah because otherwise I can't create them. Apparently App IDs are global and not account specific.

**Comment by SlayterDev** [comment]
Also I may need an email thats not an Apple ID

**Comment by Danwakeem** [comment]
Huh that is strange. Oh well I deleted everything. Okay if you do here is my yahoo: Danwakeem@yahoo.com

**Comment by SlayterDev** [comment]
Ok so that works. Super inconvenient. What you have to do is verify the account in your email. Then in preferences in Xcode I think you can add that account as a developer and it shouldn't(from what I can tell) mess with your real developer account. And hopefully you can get the proper credentials for running Enigma without much issue.

**Comment by Danwakeem** [comment]
Okay cool I will try it out when I get home and close this if it works. Thanks man!

**Comment by Danwakeem** [comment]
Well I know it will work but I'll just keep it open until I get it working on my machine.. You know what I mean😎

**Comment by SlayterDev** [comment]
Haha yeah I know what you mean :+1: I still need an email address from @jakesinger though

**Comment by SlayterDev** [comment]
If the dev profile I sent is working for everybody let me know so we can close this issue.

**Comment by Danwakeem** [comment]
Appears to be working for me



— Dan

**Comment by jakesinger** [comment]
Works for me!

**Comment by SlayterDev** [comment]
Closed it is then!

**Comment by Danwakeem** [comment]
Actually sorry I just tried to run the app on my phone and it says application could not be verified. That is probably because you would have to add our phones to your list of devices in the member center right?

**Comment by jakesinger** [comment]
This means that you need to delete the app off of your phone and re-build it. The problem arises due to the build on your phone having a different account attached to it than the one you are building.

**Comment by Danwakeem** [comment]
Oh jeez duh! Sorry my bad. Thanks Jake!
