### ISSUE TITLE
Make the profile list functional

### ISSUE THREAD

**Issue by jakesinger** [Danwakeem/enigma#55]
With my last pull from the app branch into develop, there is no ability to manage the profiles stored in CoreData.

**Comment by Danwakeem** [comment]
I think you may have over written the CoreData stuff that I added to make a new profile when you merged. Was that intentional or was that the result of an auto merge?

**Comment by SlayterDev** [comment]
Looks like it was overwritten but you can see everything that is needed here: https://github.com/Danwakeem/enigma/commit/c75faa55b882b6e3b4b62760d5705a6d4cfda496

**Comment by jakesinger** [comment]
It was intentional. I kept a copy of the old version on my system for easy reference though.

**Comment by Danwakeem** [comment]
Oh okay just making sure!

**Comment by jakesinger** [comment]
The profile list is now fully functional, with the current restriction of only having one encryption method per profile.
