### ISSUE TITLE
Integrate settings into keyboard

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#61]
Make settings take effect in keyboard usage.

**Comment by SlayterDev** [comment]
Quick period settings work. Need to wait for profile code to hook that up. Also need to figure out how color schemes are gonna work.

**Comment by SlayterDev** [comment]
Added Profile swiping to keyboard. Once color schemes are done, I will close this.

**Comment by Danwakeem** [comment]
I should have the color schemes done this weekend. 




Dan



—

**Comment by Danwakeem** [comment]
Done.
