### ISSUE TITLE
Crash in Keyboard profile list view

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#67]
func configureCell(cell: UITableViewCell, atIndexPath indexPath: NSIndexPath) {
        let object = self.fetchedResultsController.objectAtIndexPath(indexPath) as NSManagedObject
        cell.textLabel?.text = object.valueForKey("name")!.description // <<<<< This line
    }

Error states: 

*** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0xd000000000040000 <x-coredata://C0B77ADB-15B2-4CEC-80E8-EA7971A83567/Profiles/p1>''

**Comment by Danwakeem** [comment]
Try uninstalling the app then reinstalling. I was getting that error a minute ago but uninstalling then reinstalling seemed to fix it

**Comment by SlayterDev** [comment]
That fixed it.

This is awesome!

**Comment by Danwakeem** [comment]
Yeah I don't know why that happened but I think it had something to do with the changes in the containing app because when I reopened it it took me through the tutorial again so I was assuming some core data value was reset somewhere.

**Comment by SlayterDev** [comment]
It took you through the tutorial again because I switched us to the app group user defaults.

**Comment by Danwakeem** [comment]
Ohh okay gotcha

**Comment by Danwakeem** [comment]
Okay it seems to crash every time you make a change to the profiles in the containing app. Not sure why yet but I will fix this.
