### ISSUE TITLE
Containing app crashed in Landscape

### ISSUE THREAD

**Issue by Danwakeem** [Danwakeem/enigma#70]
It doesn't seem to crash on the iPhone 5 but if you try to open the app in landscape mode on the 6+ it crashes. 
![screen shot 2015-03-31 at 11 03 55 am](https://cloud.githubusercontent.com/assets/1753824/6923167/a9988710-d795-11e4-833f-71bc8165ec1b.png)

**Comment by jakesinger** [comment]
I'm pretty sure I know exactly what is going on. I made the collection view cell take the width of the device minus 40 as its width on view layout, forgetting that the 6+ puts the master view to the left.

**Comment by jakesinger** [comment]
Fixed the issue, turns out that I was assuming a profile would be selected once the `ProfileDetailViewController` loaded, so when `fetchEncryptions` was called in `viewDidLoad`, it freaked out.

**Comment by jakesinger** [comment]
I also fixed the layout as mentioned above such that the cell width is based off of the bounds of the `ProfileDetailViewController`'s view, not `UIScreen`.
